# Generated by Django 4.2.3 on 2023-07-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_board_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='loaded_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
